import ThemeLoader from "@/components/ThemeLoader";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="p-5">
            <div>Example of 2 customers</div>

            <div className="flex gap-4 mb-4">
              <Link className="border px-2 py-1.5" href="/?userId=customerA">
                customerA
              </Link>
              <Link className="border px-2 py-1.5" href="/?userId=customerB">
                customerB
              </Link>
            </div>

            <ThemeLoader />

            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
